# DNS records for purrmeowca.com.
#
# These resources are written to match what already exists in the live zone
# (captured 2026-06-20). Each one is imported into Terraform state — see
# README.md for the import commands — rather than created fresh, so apply
# the import step before running `terraform plan` for the first time.

# ---------------------------------------------------------------------------
# Apex + www AAAA, and the media CNAME, are NOT managed here.
#
# Cloudflare marks them read-only via the standard DNS API:
#   - apex/www AAAA ("100::") are generated by Workers Custom Domains
#     routing (see `origin_worker_id` in the record metadata) — managed via
#     `wrangler.toml` / the Workers dashboard, not DNS.
#   - media CNAME is generated by the R2 bucket's public-access
#     configuration — managed via the R2 bucket settings, not DNS.
#
# Attempting to manage them as cloudflare_record resources fails with
# "Unable to edit this record as this has been configured as read only."
# If/when this repo grows R2/Workers resources (see Roadmap in README),
# those resources will own this DNS state instead, via their own
# provider-managed attachment (e.g. a custom domain block on the Worker,
# or the R2 bucket's public access config) rather than a raw DNS record.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# MX route1/2/3 (apex) and the cf2024-1._domainkey TXT are NOT managed here.
#
# They belong to Cloudflare Email Routing, which owns and writes these DNS
# records itself when Email Routing is configured (Dashboard > Email >
# Email Routing). The standard DNS API rejects edits to them:
#   "This record is managed by Email Routing. Disable Email Routing to
#    modify/remove this record." (Cloudflare error 1046)
#
# Only the `send.purrmeowca.com` records below — used for outbound mail via
# Amazon SES via Resend — are plain, Terraform-manageable DNS records.
# ---------------------------------------------------------------------------
resource "cloudflare_record" "mx_send_ses" {
  zone_id  = var.zone_id
  name     = "send"
  type     = "MX"
  content  = "feedback-smtp.us-east-1.amazonses.com"
  priority = 10
  proxied  = false
  ttl      = 1
}

# ---------------------------------------------------------------------------
# SPF / DKIM / DMARC — email authentication.
# ---------------------------------------------------------------------------
resource "cloudflare_record" "spf_apex" {
  zone_id = var.zone_id
  name    = var.domain
  type    = "TXT"
  content = "v=spf1 include:_spf.mx.cloudflare.net include:amazonses.com ~all"
  proxied = false
  ttl     = 1
}

resource "cloudflare_record" "spf_send" {
  zone_id = var.zone_id
  name    = "send"
  type    = "TXT"
  content = "v=spf1 include:amazonses.com ~all"
  proxied = false
  ttl     = 1
}

resource "cloudflare_record" "dmarc" {
  zone_id = var.zone_id
  name    = "_dmarc"
  type    = "TXT"
  content = "v=DMARC1; p=none; rua=mailto:0824d557c0e34c3a94ee46a64d59a2e3@dmarc-reports.cloudflare.net; pct=100; aspf=r; adkim=r"
  proxied = false
  ttl     = 1
}

resource "cloudflare_record" "dkim_resend" {
  zone_id = var.zone_id
  name    = "resend._domainkey"
  type    = "TXT"
  content = "p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDhOe780CbKhorHWkHeAI+BQiI2y8GzoFDYkaW+pzUd3vg5cTy1dCf3NsuHw7WrBilzrrSUssHq0x3x/qK0oABbmeBebN1s/G3OKa9aW+bRSEf4+16umRhO37cvQejDwUbdRoE0T/LT1iQk1UILdPg+5IDfk4gk/eCMpBeKHIjV3wIDAQAB"
  proxied = false
  ttl     = 1
}
